language: python  

python:
 - 3.6

services: 
 - postgresql

addons:
  postgresql: "9.4"

env:
 - DJANGO=2.1.2 DB=postgres

before_install:
 - export DJANGO_SETTINGS_MODULE=authors.settings
 - export PYTHONPATH=/home/travis/build/lostlite/ah-django
 - export PIP_USE_MIRRORS=true

install:
 - pip install -r requirements.txt
 - pip install psycopg2 --quiet


before_script:
 - psql -c 'create database ah_django;' -U postgres
 - python manage.py makemigrations
 - python manage.py migrate

script: 
 #- python manage.py test
 - coverage run manage.py test

after_success: coveralls
