language: python  

python:
 - "3.6"

services: 
 - postgresql

env:
 - DJANGO=2.1.2 DB=postgres

before_install:
 - sudo apt-get update
 - sudo apt-get install python3

install:
 - pip install -r requirements.txt

before_script:
 - psql -c 'create database ah-django;' -U postgres
 
script:
 - python manage.py makemigrations
 - python manage.py test

 cache: pip